/* =========================================================================
   Deep H. Makadiya — A QUOTE FOR EVERY DAY OF THE YEAR.

   One line per day, keyed by month and day: "MM-DD". The Noticeboard reads
   today's date and shows the line that matches; 29 February has its own, so
   a leap year is covered.

   TO CHANGE A DAY'S QUOTE, edit that one line — the words first, then who
   said them. Nothing else in the site needs touching.

   A WORD ON THE ATTRIBUTIONS. These are the forms in which the lines are
   commonly quoted. Several are translations, whose exact wording differs
   between sources, and a few famous lines are traditional attributions
   rather than ones traced to a page in a book. Correct any that you know
   better — this file is yours to edit.

   Only this file is loaded for the quote, and only by the Noticeboard.
   ========================================================================= */
var QUOTES = {

  /* ---- January ---- */
  "01-01": { q: "Mathematics is the queen of the sciences, and number theory is the queen of mathematics.", who: "Carl Friedrich Gauss" },
  "01-02": { q: "God made the integers; all else is the work of man.", who: "Leopold Kronecker" },
  "01-03": { q: "We must know. We will know.", who: "David Hilbert" },
  "01-04": { q: "The essence of mathematics lies in its freedom.", who: "Georg Cantor" },
  "01-05": { q: "A mathematician is a device for turning coffee into theorems.", who: "Alfréd Rényi" },
  "01-06": { q: "Mathematics is the art of giving the same name to different things.", who: "Henri Poincaré" },
  "01-07": { q: "A mathematician, like a painter or a poet, is a maker of patterns.", who: "G. H. Hardy" },
  "01-08": { q: "Beauty is the first test: there is no permanent place in the world for ugly mathematics.", who: "G. H. Hardy" },
  "01-09": { q: "Logic is the hygiene the mathematician practises to keep his ideas healthy and strong.", who: "Hermann Weyl" },
  "01-10": { q: "The book of nature is written in the language of mathematics.", who: "Galileo Galilei" },
  "01-11": { q: "Geometry is knowledge of the eternally existent.", who: "Plato" },
  "01-12": { q: "There is no royal road to geometry.", who: "Euclid" },
  "01-13": { q: "Give me a place to stand and I will move the Earth.", who: "Archimedes" },
  "01-14": { q: "If I have seen further it is by standing on the shoulders of giants.", who: "Isaac Newton" },
  "01-15": { q: "Each problem that I solved became a rule which served afterwards to solve other problems.", who: "René Descartes" },
  "01-16": { q: "The last thing one settles in writing a book is what one should put in first.", who: "Blaise Pascal" },
  "01-17": { q: "Nothing takes place in the world whose meaning is not that of some maximum or minimum.", who: "Leonhard Euler" },
  "01-18": { q: "Now I will have fewer distractions.", who: "Leonhard Euler, on losing the sight of an eye" },
  "01-19": { q: "Read Euler, read Euler, he is the master of us all.", who: "Pierre-Simon Laplace" },
  "01-20": { q: "It is India that gave us the ingenious method of expressing all numbers by means of ten symbols.", who: "Pierre-Simon Laplace" },
  "01-21": { q: "Mathematics is the science of what is clear by itself.", who: "Carl Gustav Jacob Jacobi" },
  "01-22": { q: "God ever arithmetizes.", who: "Carl Gustav Jacob Jacobi" },
  "01-23": { q: "One must always invert.", who: "Carl Gustav Jacob Jacobi" },
  "01-24": { q: "Tell her to wait a moment — I am almost done.", who: "Carl Friedrich Gauss, when told his wife was dying" },
  "01-25": { q: "I have had my results for a long time, but I do not yet know how I am to arrive at them.", who: "Carl Friedrich Gauss" },
  "01-26": { q: "It is not knowledge, but the act of learning, that grants the greatest enjoyment.", who: "Carl Friedrich Gauss" },
  "01-27": { q: "Abel has left mathematicians enough to keep them busy for five hundred years.", who: "Charles Hermite" },
  "01-28": { q: "He who seeks for methods without having a definite problem in mind seeks for the most part in vain.", who: "David Hilbert" },
  "01-29": { q: "No one shall expel us from the paradise that Cantor has created.", who: "David Hilbert" },
  "01-30": { q: "Physics is much too hard for physicists.", who: "David Hilbert" },
  "01-31": { q: "One geometry cannot be more true than another; it can only be more convenient.", who: "Henri Poincaré" },

  /* ---- February ---- */
  "02-01": { q: "Mathematics is the most beautiful and most powerful creation of the human spirit.", who: "Stefan Banach" },
  "02-02": { q: "A mathematician is a person who can find analogies between theorems; a better mathematician one who sees analogies between proofs.", who: "Stefan Banach" },
  "02-03": { q: "Good mathematicians see analogies between theorems; great ones see analogies between analogies.", who: "Stefan Banach" },
  "02-04": { q: "In mathematics you don't understand things. You just get used to them.", who: "John von Neumann" },
  "02-05": { q: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", who: "John von Neumann" },
  "02-06": { q: "There's no sense in being precise when you don't even know what you're talking about.", who: "John von Neumann" },
  "02-07": { q: "The best material model of a cat is another, or preferably the same, cat.", who: "Norbert Wiener" },
  "02-08": { q: "Mathematics is too important to be left to the mathematicians.", who: "Norbert Wiener" },
  "02-09": { q: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", who: "Alan Turing" },
  "02-10": { q: "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.", who: "Alan Turing" },
  "02-11": { q: "The universe is not only queerer than we suppose, but queerer than we can suppose.", who: "J. B. S. Haldane" },
  "02-12": { q: "What is best in mathematics deserves not merely to be learnt as a task, but to be assimilated as a part of daily thought.", who: "Bertrand Russell" },
  "02-13": { q: "Mathematics may be defined as the subject in which we never know what we are talking about, nor whether what we are saying is true.", who: "Bertrand Russell" },
  "02-14": { q: "Everything of importance has been said before by somebody who did not discover it.", who: "Alfred North Whitehead" },
  "02-15": { q: "Civilization advances by extending the number of important operations which we can perform without thinking about them.", who: "Alfred North Whitehead" },
  "02-16": { q: "It is a profoundly erroneous truism that we should cultivate the habit of thinking of what we are doing.", who: "Alfred North Whitehead" },
  "02-17": { q: "An equation for me has no meaning unless it expresses a thought of God.", who: "Srinivasa Ramanujan" },
  "02-18": { q: "Every positive integer is one of Ramanujan's personal friends.", who: "J. E. Littlewood" },
  "02-19": { q: "A good mathematical joke is better, and better mathematics, than a dozen mediocre papers.", who: "J. E. Littlewood" },
  "02-20": { q: "The mathematician's patterns, like the painter's or the poet's, must be beautiful.", who: "G. H. Hardy" },
  "02-21": { q: "I believe that mathematical reality lies outside us, and that our function is to discover or observe it.", who: "G. H. Hardy" },
  "02-22": { q: "The calculus was the first achievement of modern mathematics, and it is difficult to overestimate its importance.", who: "John von Neumann" },
  "02-23": { q: "Mathematics is not a deductive science — that's a cliché. When you try to prove a theorem, you don't just list the hypotheses and start to reason. You try, you fail. You experiment. You guess.", who: "Paul Halmos" },
  "02-24": { q: "The heart of mathematics is its problems.", who: "Paul Halmos" },
  "02-25": { q: "The only way to learn mathematics is to do mathematics.", who: "Paul Halmos" },
  "02-26": { q: "Don't just read it; fight it! Ask your own questions, look for your own examples, discover your own proofs.", who: "Paul Halmos" },
  "02-27": { q: "If you can't solve a problem, then there is an easier problem you can solve: find it.", who: "George Pólya" },
  "02-28": { q: "A great discovery solves a great problem, but there is a grain of discovery in the solution of any problem.", who: "George Pólya" },
  "02-29": { q: "It is better to solve one problem five different ways than to solve five problems one way.", who: "George Pólya" },

  /* ---- March ---- */
  "03-01": { q: "Mathematics is the cheapest science. Unlike physics or chemistry, it does not require any expensive equipment. All one needs is a pencil and paper.", who: "George Pólya" },
  "03-02": { q: "First, understand the problem. Then make a plan. Then carry out the plan. Then look back.", who: "George Pólya" },
  "03-03": { q: "Everyone knows what a curve is, until he has studied enough mathematics to become confused.", who: "Felix Klein" },
  "03-04": { q: "Mathematics in general is fundamentally the science of self-evident things.", who: "Felix Klein" },
  "03-05": { q: "My brain is open.", who: "Paul Erdős" },
  "03-06": { q: "A mathematician is a machine for turning coffee into theorems.", who: "Paul Erdős, quoting Alfréd Rényi" },
  "03-07": { q: "This one is from The Book.", who: "Paul Erdős, on a particularly elegant proof" },
  "03-08": { q: "Why are numbers beautiful? It's like asking why is Beethoven's Ninth Symphony beautiful.", who: "Paul Erdős" },
  "03-09": { q: "It is not enough to be in the right place at the right time. You should also have an open mind at the right time.", who: "Paul Erdős" },
  "03-10": { q: "The problems worthy of attack prove their worth by hitting back.", who: "Piet Hein" },
  "03-11": { q: "The road to wisdom? Well, it's plain and simple to express: err and err and err again, but less and less and less.", who: "Piet Hein" },
  "03-12": { q: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", who: "Antoine de Saint-Exupéry" },
  "03-13": { q: "Mathematics is the science of patterns.", who: "Lynn Arthur Steen" },
  "03-14": { q: "Mathematics is not about numbers, equations, computations or algorithms: it is about understanding.", who: "William Thurston" },
  "03-15": { q: "What we are doing is finding ways for people to understand and think about mathematics.", who: "William Thurston" },
  "03-16": { q: "Mathematics is a social construction as well as a mental one — it lives in the community of mathematicians.", who: "William Thurston" },
  "03-17": { q: "The rapid advance of mathematics rests on the shoulders of its unsolved problems.", who: "David Hilbert" },
  "03-18": { q: "The art of doing mathematics consists in finding that special case which contains all the germs of generality.", who: "David Hilbert" },
  "03-19": { q: "Mathematical science is in my opinion an indivisible whole, an organism whose vitality is conditioned upon the connection of its parts.", who: "David Hilbert" },
  "03-20": { q: "Begin at the beginning and go on till you come to the end: then stop.", who: "Lewis Carroll" },
  "03-21": { q: "Contrariwise, if it was so, it might be; and if it were so, it would be; but as it isn't, it ain't. That's logic.", who: "Lewis Carroll" },
  "03-22": { q: "The theory of numbers is the last great uncivilized continent of mathematics.", who: "Eric Temple Bell" },
  "03-23": { q: "Obvious is the most dangerous word in mathematics.", who: "Eric Temple Bell" },
  "03-24": { q: "Guided only by their feeling for symmetry, simplicity and generality, and an indefinable sense of the fitness of things, creative mathematicians now, as in the past, are inspired by the art of mathematics.", who: "Eric Temple Bell" },
  "03-25": { q: "The mathematician does not study pure mathematics because it is useful; he studies it because he delights in it, and he delights in it because it is beautiful.", who: "Henri Poincaré" },
  "03-26": { q: "It is by logic that we prove, but by intuition that we discover.", who: "Henri Poincaré" },
  "03-27": { q: "Thought is only a flash in the middle of a long night, but the flash that means everything.", who: "Henri Poincaré" },
  "03-28": { q: "Mathematics is the art of reducing any problem to linear algebra.", who: "William Stein" },
  "03-29": { q: "To ask the right question is harder than to answer it.", who: "Georg Cantor" },
  "03-30": { q: "In mathematics the art of proposing a question must be held of higher value than solving it.", who: "Georg Cantor" },
  "03-31": { q: "The fear of infinity is a form of myopia that destroys the possibility of seeing the actual infinite.", who: "Georg Cantor" },

  /* ---- April ---- */
  "04-01": { q: "I see it, but I don't believe it.", who: "Georg Cantor, on a result about dimension" },
  "04-02": { q: "A mathematical theory is not to be considered complete until you have made it so clear that you can explain it to the first man whom you meet on the street.", who: "David Hilbert" },
  "04-03": { q: "Simplicity is the ultimate sophistication.", who: "Leonardo da Vinci" },
  "04-04": { q: "Mechanics is the paradise of the mathematical sciences.", who: "Leonardo da Vinci" },
  "04-05": { q: "Nature is written in mathematical language.", who: "Galileo Galilei" },
  "04-06": { q: "Measure what is measurable, and make measurable what is not so.", who: "Galileo Galilei" },
  "04-07": { q: "Where there is matter, there is geometry.", who: "Johannes Kepler" },
  "04-08": { q: "Geometry has two great treasures: one is the theorem of Pythagoras, the other the division of a line into extreme and mean ratio.", who: "Johannes Kepler" },
  "04-09": { q: "The chief aim of all investigations of the external world should be to discover the rational order and harmony imposed on it by God.", who: "Johannes Kepler" },
  "04-10": { q: "Nature uses as little as possible of anything.", who: "Johannes Kepler" },
  "04-11": { q: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", who: "Isaac Newton" },
  "04-12": { q: "I do not know what I may appear to the world, but to myself I seem to have been only like a boy playing on the sea-shore.", who: "Isaac Newton" },
  "04-13": { q: "Plato is my friend, Aristotle is my friend, but my best friend is truth.", who: "Isaac Newton" },
  "04-14": { q: "No great discovery was ever made without a bold guess.", who: "Isaac Newton" },
  "04-15": { q: "I have discovered a truly marvellous proof of this, which this margin is too narrow to contain.", who: "Pierre de Fermat" },
  "04-16": { q: "It is impossible to separate a cube into two cubes, or a fourth power into two fourth powers.", who: "Pierre de Fermat" },
  "04-17": { q: "In mathematics there are no true controversies.", who: "Carl Friedrich Gauss" },
  "04-18": { q: "Life stands before me like an eternal spring with new and brilliant clothes.", who: "Carl Friedrich Gauss" },
  "04-19": { q: "The enchanting charms of this sublime science reveal themselves in all their beauty only to those who have the courage to go deeply into it.", who: "Carl Friedrich Gauss" },
  "04-20": { q: "I confess that Fermat's Theorem as an isolated proposition has very little interest for me.", who: "Carl Friedrich Gauss" },
  "04-21": { q: "Mathematics is the tool specially suited for dealing with abstract concepts of any kind.", who: "Paul Dirac" },
  "04-22": { q: "God used beautiful mathematics in creating the world.", who: "Paul Dirac" },
  "04-23": { q: "It is more important to have beauty in one's equations than to have them fit experiment.", who: "Paul Dirac" },
  "04-24": { q: "The most incomprehensible thing about the world is that it is comprehensible.", who: "Albert Einstein" },
  "04-25": { q: "As far as the laws of mathematics refer to reality, they are not certain; and as far as they are certain, they do not refer to reality.", who: "Albert Einstein" },
  "04-26": { q: "Pure mathematics is, in its way, the poetry of logical ideas.", who: "Albert Einstein" },
  "04-27": { q: "Do not worry about your difficulties in mathematics. I can assure you mine are still greater.", who: "Albert Einstein" },
  "04-28": { q: "Everything should be made as simple as possible, but not simpler.", who: "Albert Einstein" },
  "04-29": { q: "The unreasonable effectiveness of mathematics in the natural sciences is a wonderful gift which we neither understand nor deserve.", who: "Eugene Wigner" },
  "04-30": { q: "Mathematics is the science of skilful operations with concepts and rules invented just for this purpose.", who: "Eugene Wigner" },

  /* ---- May ---- */
  "05-01": { q: "Number rules the universe.", who: "Pythagoras" },
  "05-02": { q: "There is geometry in the humming of the strings, there is music in the spacing of the spheres.", who: "Pythagoras" },
  "05-03": { q: "All is number.", who: "Pythagoras" },
  "05-04": { q: "The laws of nature are but the mathematical thoughts of God.", who: "Euclid" },
  "05-05": { q: "What has been proved without reason can be denied without reason.", who: "Euclid" },
  "05-06": { q: "Do not disturb my circles.", who: "Archimedes" },
  "05-07": { q: "Eureka!", who: "Archimedes" },
  "05-08": { q: "The shortest path between two truths in the real domain passes through the complex domain.", who: "Jacques Hadamard" },
  "05-09": { q: "Practical application is found by not looking for it, and one can say that the whole progress of civilization rests on that principle.", who: "Jacques Hadamard" },
  "05-10": { q: "Logic sometimes makes monsters.", who: "Henri Poincaré" },
  "05-11": { q: "Later generations will regard set theory as a disease from which one has recovered.", who: "Henri Poincaré" },
  "05-12": { q: "Mathematicians do not study objects, but relations between objects.", who: "Henri Poincaré" },
  "05-13": { q: "Science is built up of facts, as a house is built of stones; but an accumulation of facts is no more a science than a heap of stones is a house.", who: "Henri Poincaré" },
  "05-14": { q: "If nature were not beautiful, it would not be worth knowing, and life would not be worth living.", who: "Henri Poincaré" },
  "05-15": { q: "Mathematics is a presuppositionless science.", who: "David Hilbert" },
  "05-16": { q: "One should always generalize.", who: "Carl Gustav Jacob Jacobi" },
  "05-17": { q: "The true method of foresight consists in the general form of the mathematical process.", who: "Alfred North Whitehead" },
  "05-18": { q: "The science of pure mathematics may claim to be the most original creation of the human spirit.", who: "Alfred North Whitehead" },
  "05-19": { q: "Symbolism is useful because it makes things difficult.", who: "Alfred North Whitehead" },
  "05-20": { q: "Algebra is the intellectual instrument for rendering clear the quantitative aspects of the world.", who: "Alfred North Whitehead" },
  "05-21": { q: "It requires a very unusual mind to undertake the analysis of the obvious.", who: "Alfred North Whitehead" },
  "05-22": { q: "Mathematics is the science of order and measure.", who: "René Descartes" },
  "05-23": { q: "Divide each difficulty into as many parts as is feasible and necessary to resolve it.", who: "René Descartes" },
  "05-24": { q: "It is not enough to have a good mind; the main thing is to use it well.", who: "René Descartes" },
  "05-25": { q: "Perfect numbers, like perfect men, are very rare.", who: "René Descartes" },
  "05-26": { q: "The two operations of our understanding, intuition and deduction, on which alone we have said we must rely.", who: "René Descartes" },
  "05-27": { q: "The imaginary number is a fine and wonderful resource of the human spirit, almost an amphibian between being and not being.", who: "Gottfried Wilhelm Leibniz" },
  "05-28": { q: "There is nothing without a reason.", who: "Gottfried Wilhelm Leibniz" },
  "05-29": { q: "Music is the pleasure the human soul experiences from counting without being aware that it is counting.", who: "Gottfried Wilhelm Leibniz" },
  "05-30": { q: "In symbols one observes an advantage in discovery which is greatest when they express the exact nature of a thing briefly.", who: "Gottfried Wilhelm Leibniz" },
  "05-31": { q: "Nothing is more important than to see the sources of invention which are, in my opinion, more interesting than the inventions themselves.", who: "Gottfried Wilhelm Leibniz" },

  /* ---- June ---- */
  "06-01": { q: "The infinite! No other question has ever moved so profoundly the spirit of man.", who: "David Hilbert" },
  "06-02": { q: "Mathematics knows no races or geographic boundaries; for mathematics, the cultural world is one country.", who: "David Hilbert" },
  "06-03": { q: "We hear within us the perpetual call: there is the problem. Seek its solution.", who: "David Hilbert" },
  "06-04": { q: "How can it be that mathematics, being after all a product of human thought independent of experience, is so admirably adapted to the objects of reality?", who: "Albert Einstein" },
  "06-05": { q: "The mathematics is not there till we put it there.", who: "Arthur Eddington" },
  "06-06": { q: "Proof is the idol before whom the pure mathematician tortures himself.", who: "Arthur Eddington" },
  "06-07": { q: "Mathematics is the most exact science, and its conclusions are capable of absolute proof.", who: "Charles Proteus Steinmetz" },
  "06-08": { q: "The moving power of mathematical invention is not reasoning but imagination.", who: "Augustus De Morgan" },
  "06-09": { q: "Great fleas have little fleas upon their backs to bite 'em, and little fleas have lesser fleas, and so ad infinitum.", who: "Augustus De Morgan" },
  "06-10": { q: "It is easier to square the circle than to get round a mathematician.", who: "Augustus De Morgan" },
  "06-11": { q: "No science doubts, no mathematics disputes.", who: "Augustus De Morgan" },
  "06-12": { q: "The mathematician is fascinated with the marvellous beauty of the forms he constructs.", who: "Nikolai Lobachevsky" },
  "06-13": { q: "There is no branch of mathematics, however abstract, which may not some day be applied to phenomena of the real world.", who: "Nikolai Lobachevsky" },
  "06-14": { q: "Out of nothing I have created a strange new universe.", who: "János Bolyai" },
  "06-15": { q: "Mathematics is the science which draws necessary conclusions.", who: "Benjamin Peirce" },
  "06-16": { q: "Mathematics is the study of ideal constructions, and of the discovery of relations between them.", who: "Charles Sanders Peirce" },
  "06-17": { q: "The one thing that marks the true artist is a clear perception and firm command of technique.", who: "Charles Sanders Peirce" },
  "06-18": { q: "Mathematics is the purest of the arts, as well as the most misunderstood.", who: "Paul Lockhart" },
  "06-19": { q: "A mathematician, like a painter or poet, works with ideas.", who: "Paul Lockhart" },
  "06-20": { q: "Mathematics is the music of reason.", who: "James Joseph Sylvester" },
  "06-21": { q: "May not music be described as the mathematics of the sense, mathematics as music of the reason?", who: "James Joseph Sylvester" },
  "06-22": { q: "It is the constant aim of the mathematician to reduce all his expressions to their lowest terms.", who: "James Joseph Sylvester" },
  "06-23": { q: "The world of ideas which mathematics discloses is neither created nor invented, but discovered.", who: "James Joseph Sylvester" },
  "06-24": { q: "As for everything else, so for a mathematical theory: beauty can be perceived but not explained.", who: "Arthur Cayley" },
  "06-25": { q: "Projective geometry is all geometry.", who: "Arthur Cayley" },
  "06-26": { q: "Time is said to have only one dimension, and space to have three dimensions. The mathematical quaternion partakes of both these elements.", who: "William Rowan Hamilton" },
  "06-27": { q: "Who would not rather have the fame of Archimedes than that of his conqueror Marcellus?", who: "William Rowan Hamilton" },
  "06-28": { q: "No one before had thought of measuring quality as one measures quantity.", who: "George Boole" },
  "06-29": { q: "It is not of the essence of mathematics to be occupied with the ideas of number and quantity.", who: "George Boole" },
  "06-30": { q: "Probability is expectation founded upon partial knowledge.", who: "George Boole" },

  /* ---- July ---- */
  "07-01": { q: "It is impossible to be a mathematician without being a poet in soul.", who: "Sofia Kovalevskaya" },
  "07-02": { q: "Say what you know, do what you must, come what may.", who: "Sofia Kovalevskaya" },
  "07-03": { q: "Many who have never had the occasion to learn what mathematics is confuse it with arithmetic and consider it a dry and arid science.", who: "Sofia Kovalevskaya" },
  "07-04": { q: "My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously.", who: "Emmy Noether" },
  "07-05": { q: "If one proves the equality of two numbers a and b by showing first that a is less than or equal to b and then that b is less than or equal to a, it is unfair; one should instead show that they are really equal by disclosing the inner ground for their equality.", who: "Emmy Noether" },
  "07-06": { q: "The development of mathematics toward greater precision has led to the formalization of large tracts of it.", who: "Kurt Gödel" },
  "07-07": { q: "Either mathematics is too big for the human mind, or the human mind is more than a machine.", who: "Kurt Gödel" },
  "07-08": { q: "The meaning of the world is the separation of wish and fact.", who: "Kurt Gödel" },
  "07-09": { q: "I don't believe in natural science.", who: "Kurt Gödel" },
  "07-10": { q: "A set is a Many that allows itself to be thought of as a One.", who: "Georg Cantor" },
  "07-11": { q: "Mathematics is the science of the infinite.", who: "Hermann Weyl" },
  "07-12": { q: "My work always tried to unite the true with the beautiful, but when I had to choose one or the other, I usually chose the beautiful.", who: "Hermann Weyl" },
  "07-13": { q: "The problems of mathematics are not problems in a vacuum.", who: "Hermann Weyl" },
  "07-14": { q: "Numbers measure size, groups measure symmetry.", who: "Mark Ronan" },
  "07-15": { q: "Symmetry, as wide or as narrow as you may define its meaning, is one idea by which man through the ages has tried to comprehend and create order, beauty and perfection.", who: "Hermann Weyl" },
  "07-16": { q: "Mathematics is much more than a language for dealing with the physical world.", who: "Ronald Graham" },
  "07-17": { q: "The purpose of computing is insight, not numbers.", who: "Richard Hamming" },
  "07-18": { q: "Mathematics is not merely an idle art form, it is an essential part of our society.", who: "Richard Hamming" },
  "07-19": { q: "In science, if you know what you are doing, you should not be doing it.", who: "Richard Hamming" },
  "07-20": { q: "The most important thing to do is to work on important problems.", who: "Richard Hamming" },
  "07-21": { q: "Premature optimization is the root of all evil.", who: "Donald Knuth" },
  "07-22": { q: "Science is what we understand well enough to explain to a computer. Art is everything else we do.", who: "Donald Knuth" },
  "07-23": { q: "Beware of bugs in the above code; I have only proved it correct, not tried it.", who: "Donald Knuth" },
  "07-24": { q: "An algorithm must be seen to be believed.", who: "Donald Knuth" },
  "07-25": { q: "Everything is vague to a degree you do not realize till you have tried to make it precise.", who: "Bertrand Russell" },
  "07-26": { q: "Testing shows the presence, not the absence of bugs.", who: "Edsger W. Dijkstra" },
  "07-27": { q: "Computer science is no more about computers than astronomy is about telescopes.", who: "Edsger W. Dijkstra" },
  "07-28": { q: "Simplicity is prerequisite for reliability.", who: "Edsger W. Dijkstra" },
  "07-29": { q: "The question of whether machines can think is about as relevant as the question of whether submarines can swim.", who: "Edsger W. Dijkstra" },
  "07-30": { q: "Elegance is not a dispensable luxury but a quality that decides between success and failure.", who: "Edsger W. Dijkstra" },
  "07-31": { q: "Clouds are not spheres, mountains are not cones, coastlines are not circles.", who: "Benoit Mandelbrot" },

  /* ---- August ---- */
  "08-01": { q: "Bottomless wonders spring from simple rules, which are repeated without end.", who: "Benoit Mandelbrot" },
  "08-02": { q: "Beautiful, damn hard, increasingly useful. That's fractals.", who: "Benoit Mandelbrot" },
  "08-03": { q: "A fractal is a way of seeing infinity.", who: "James Gleick" },
  "08-04": { q: "Chaos: when the present determines the future, but the approximate present does not approximately determine the future.", who: "Edward Lorenz" },
  "08-05": { q: "Nature laughs at the difficulties of integration.", who: "Pierre-Simon Laplace" },
  "08-06": { q: "What we know is not much. What we do not know is immense.", who: "Pierre-Simon Laplace" },
  "08-07": { q: "The theory of probabilities is at bottom nothing but common sense reduced to calculus.", who: "Pierre-Simon Laplace" },
  "08-08": { q: "The weight of evidence for an extraordinary claim must be proportioned to its strangeness.", who: "Pierre-Simon Laplace" },
  "08-09": { q: "The profound study of nature is the most fertile source of mathematical discoveries.", who: "Joseph Fourier" },
  "08-10": { q: "Mathematics compares the most diverse phenomena and discovers the secret analogies that unite them.", who: "Joseph Fourier" },
  "08-11": { q: "When we ask advice, we are usually looking for an accomplice.", who: "Joseph-Louis Lagrange" },
  "08-12": { q: "Newton was the greatest genius that ever existed, and the most fortunate, for we cannot find more than once a system of the world to establish.", who: "Joseph-Louis Lagrange" },
  "08-13": { q: "As long as algebra and geometry have been separated, their progress has been slow and their uses limited.", who: "Joseph-Louis Lagrange" },
  "08-14": { q: "Men pass away, but their deeds abide.", who: "Augustin-Louis Cauchy" },
  "08-15": { q: "If only I had the theorems! Then I should find the proofs easily enough.", who: "Bernhard Riemann" },
  "08-16": { q: "The mathematician is entirely free, within the limits of his imagination, to construct what worlds he pleases.", who: "J. W. N. Sullivan" },
  "08-17": { q: "Henceforth space by itself, and time by itself, are doomed to fade away into mere shadows.", who: "Hermann Minkowski" },
  "08-18": { q: "A mathematician who is not also something of a poet will never be a complete mathematician.", who: "Karl Weierstrass" },
  "08-19": { q: "It is true that a mathematician who is not somewhat of a poet will never be a perfect mathematician.", who: "Karl Weierstrass" },
  "08-20": { q: "Whoever wants to know the essence of mathematics must occupy himself with the problem of the infinite.", who: "Hermann Weyl" },
  "08-21": { q: "Number is the within of all things.", who: "Pythagoras" },
  "08-22": { q: "A mathematician's work is mostly a tangle of guesswork, analogy, wishful thinking and frustration.", who: "Paul Lockhart" },
  "08-23": { q: "There is nothing as dreamy and poetic, nothing as radical, subversive, and psychedelic, as mathematics.", who: "Paul Lockhart" },
  "08-24": { q: "Mathematics is the art of explanation, and if you deny students the chance to engage in this activity you deny them mathematics itself.", who: "Paul Lockhart" },
  "08-25": { q: "Doing mathematics should always mean finding patterns and crafting beautiful and meaningful explanations.", who: "Paul Lockhart" },
  "08-26": { q: "Wherever there is number, there is beauty.", who: "Proclus" },
  "08-27": { q: "This, therefore, is mathematics: she reminds you of the invisible form of the soul.", who: "Proclus" },
  "08-28": { q: "Mathematics is the door and key to the sciences.", who: "Roger Bacon" },
  "08-29": { q: "Neglect of mathematics works injury to all knowledge, since he who is ignorant of it cannot know the other sciences.", who: "Roger Bacon" },
  "08-30": { q: "In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.", who: "Galileo Galilei" },
  "08-31": { q: "Philosophy is written in that great book which ever lies before our eyes.", who: "Galileo Galilei" },

  /* ---- September ---- */
  "09-01": { q: "Mathematics is a place where you can do things which you can't do in the real world.", who: "Marcus du Sautoy" },
  "09-02": { q: "Mathematics is the science of patterns, and nature exploits just about every pattern that there is.", who: "Ian Stewart" },
  "09-03": { q: "The whole of mathematics is a game whose rules are invented as we go along.", who: "Ian Stewart" },
  "09-04": { q: "Mathematics is the ultimate in technology transfer.", who: "Ian Stewart" },
  "09-05": { q: "Nature is an infinite sphere whose centre is everywhere and whose circumference is nowhere.", who: "Blaise Pascal" },
  "09-06": { q: "A proof is a device of communication, not a device of intimidation.", who: "Paul Halmos" },
  "09-07": { q: "The source of all great mathematics is the special case, the concrete example.", who: "Paul Halmos" },
  "09-08": { q: "To be a scholar of mathematics you must be born with talent, insight, concentration, taste, luck, drive and the ability to visualize and guess.", who: "Paul Halmos" },
  "09-09": { q: "Applied mathematics will always need pure mathematics just as anteaters will always need ants.", who: "Paul Halmos" },
  "09-10": { q: "I like to look at mathematics almost more as an art than as a science.", who: "Michael Atiyah" },
  "09-11": { q: "Mathematics is the science of analogy, and the whole of mathematics is a search for patterns.", who: "Michael Atiyah" },
  "09-12": { q: "The aim of mathematics is to explain as much as possible in simple terms.", who: "Michael Atiyah" },
  "09-13": { q: "Algebra is the offer made by the devil to the mathematician.", who: "Michael Atiyah" },
  "09-14": { q: "Mathematics is very much like poetry — what makes a good poem is that it is a great idea expressed economically.", who: "Lipman Bers" },
  "09-15": { q: "The best problems are the ones you cannot stop thinking about.", who: "Andrew Wiles" },
  "09-16": { q: "Just because we can't find a solution, it doesn't mean there isn't one.", who: "Andrew Wiles" },
  "09-17": { q: "Perhaps I could best describe my experience of doing mathematics in terms of entering a dark mansion.", who: "Andrew Wiles" },
  "09-18": { q: "You have to be prepared to fail, over and over, and not be discouraged.", who: "Andrew Wiles" },
  "09-19": { q: "Mathematics is a language and a tool, but it is also a culture.", who: "Barry Mazur" },
  "09-20": { q: "Imagination is more important than knowledge.", who: "Albert Einstein" },
  "09-21": { q: "The beauty of mathematics only shows itself to more patient followers.", who: "Maryam Mirzakhani" },
  "09-22": { q: "I don't have any particular recipe. It is the reason why doing research is challenging as well as attractive.", who: "Maryam Mirzakhani" },
  "09-23": { q: "You have to spend some energy and effort to see the beauty of math.", who: "Maryam Mirzakhani" },
  "09-24": { q: "Life isn't supposed to be easy; it's supposed to be life.", who: "Maryam Mirzakhani" },
  "09-25": { q: "There is no mathematician so expert in his science as to place entire confidence in any truth immediately upon his discovery of it.", who: "David Hume" },
  "09-26": { q: "Mathematics is the supreme judge; from its decisions there is no appeal.", who: "Tobias Dantzig" },
  "09-27": { q: "Mathematics is not yet ready for such problems.", who: "Paul Erdős, on the Collatz conjecture" },
  "09-28": { q: "The mathematician's best work is art, a high and perfect art.", who: "Gösta Mittag-Leffler" },
  "09-29": { q: "Mathematics is not a spectator sport.", who: "George Pólya" },
  "09-30": { q: "The elegance of a mathematical theorem is directly proportional to the number of independent ideas one can see in the theorem.", who: "Stanislaw Ulam" },

  /* ---- October ---- */
  "10-01": { q: "In many cases, mathematics is an escape from reality.", who: "Stanislaw Ulam" },
  "10-02": { q: "Ask not what mathematics can do for you; ask what you can do for mathematics.", who: "Paul Erdős" },
  "10-03": { q: "Discovery consists of seeing what everybody has seen and thinking what nobody has thought.", who: "Albert Szent-Györgyi" },
  "10-04": { q: "God may not play dice with the universe, but something strange is going on with the prime numbers.", who: "Paul Erdős" },
  "10-05": { q: "It's not that I'm so smart, it's just that I stay with problems longer.", who: "Albert Einstein" },
  "10-06": { q: "Mathematics as an expression of the human mind reflects the active will, the contemplative reason, and the desire for aesthetic perfection.", who: "Richard Courant" },
  "10-07": { q: "Mathematics is not a careful march down a well-cleared highway, but a journey into a strange wilderness where the explorers often get lost.", who: "W. S. Anglin" },
  "10-08": { q: "Rigour should be a signal to the historian that the maps have been made, and the real explorers have gone elsewhere.", who: "W. S. Anglin" },
  "10-09": { q: "Mathematics, springing from the soil of basic human experience, must never be allowed to drift too far from its roots.", who: "Richard Courant" },
  "10-10": { q: "An expert is a man who has made all the mistakes which can be made in a very narrow field.", who: "Niels Bohr" },
  "10-11": { q: "Prediction is very difficult, especially about the future.", who: "Niels Bohr" },
  "10-12": { q: "The opposite of a correct statement is a false statement. But the opposite of a profound truth may well be another profound truth.", who: "Niels Bohr" },
  "10-13": { q: "There is no philosophy which is not founded upon knowledge of the phenomena, but to get any profit from this knowledge it is absolutely necessary to be a mathematician.", who: "Daniel Bernoulli" },
  "10-14": { q: "It is the nature of probability that it is not certainty.", who: "Jacob Bernoulli" },
  "10-15": { q: "Even as the finite encloses an infinite series, so the limits of the infinite always remain.", who: "Jacob Bernoulli" },
  "10-16": { q: "I shall change my course, but not my nature.", who: "Jacob Bernoulli" },
  "10-17": { q: "Mathematics reveals its secrets only to those who approach it with pure love, for its own beauty.", who: "Archimedes" },
  "10-18": { q: "Man is equal to the fraction whose numerator is what he is and the denominator what he thinks of himself.", who: "Leo Tolstoy" },
  "10-19": { q: "It is the mark of an educated mind to rest satisfied with the degree of precision which the nature of the subject admits.", who: "Aristotle" },
  "10-20": { q: "The mathematical sciences particularly exhibit order, symmetry, and limitation; and these are the greatest forms of the beautiful.", who: "Aristotle" },
  "10-21": { q: "The whole is more than the sum of its parts.", who: "Aristotle" },
  "10-22": { q: "Let no one ignorant of geometry enter here.", who: "Inscription at Plato's Academy" },
  "10-23": { q: "The knowledge at which geometry aims is the knowledge of the eternal.", who: "Plato" },
  "10-24": { q: "Arithmetic has a very great and elevating effect, compelling the soul to reason about abstract number.", who: "Plato" },
  "10-25": { q: "Mathematics is like checkers in being suitable for the young, not too difficult, amusing, and without peril to the state.", who: "Plato" },
  "10-26": { q: "Mathematics is a more powerful instrument of knowledge than any other that has been bequeathed to us by human agency.", who: "René Descartes" },
  "10-27": { q: "With me everything turns into mathematics.", who: "René Descartes" },
  "10-28": { q: "A good proof is one that makes us wiser.", who: "Yuri Manin" },
  "10-29": { q: "The universe cannot be read until we have learnt the language in which it is written.", who: "Galileo Galilei" },
  "10-30": { q: "Mathematics is the gate and key of the sciences.", who: "Roger Bacon" },
  "10-31": { q: "If I were again beginning my studies, I would follow the advice of Plato and start with mathematics.", who: "Galileo Galilei" },

  /* ---- November ---- */
  "11-01": { q: "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.", who: "S. Gudder" },
  "11-02": { q: "Mathematics is the only good metaphysics.", who: "William Thomson, Lord Kelvin" },
  "11-03": { q: "When you can measure what you are speaking about, and express it in numbers, you know something about it.", who: "William Thomson, Lord Kelvin" },
  "11-04": { q: "Do not imagine that mathematics is hard and crabbed, and repulsive to common sense.", who: "William Thomson, Lord Kelvin" },
  "11-05": { q: "A mathematician is one to whom that is as obvious as that twice two makes four is to you.", who: "William Thomson, Lord Kelvin" },
  "11-06": { q: "There is no certainty in sciences where none of the mathematical sciences can be applied.", who: "Leonardo da Vinci" },
  "11-07": { q: "Statistics is the grammar of science.", who: "Karl Pearson" },
  "11-08": { q: "All models are wrong, but some are useful.", who: "George Box" },
  "11-09": { q: "The best thing about being a statistician is that you get to play in everyone's backyard.", who: "John Tukey" },
  "11-10": { q: "An approximate answer to the right problem is worth a good deal more than an exact answer to an approximate problem.", who: "John Tukey" },
  "11-11": { q: "The greatest value of a picture is when it forces us to notice what we never expected to see.", who: "John Tukey" },
  "11-12": { q: "To call in the statistician after the experiment is done may be no more than asking him to perform a post-mortem examination.", who: "Ronald Fisher" },
  "11-13": { q: "The null hypothesis is never proved or established, but is possibly disproved.", who: "Ronald Fisher" },
  "11-14": { q: "It is easy to lie with statistics, but it is easier to lie without them.", who: "Frederick Mosteller" },
  "11-15": { q: "Probability theory is nothing but common sense reduced to calculation.", who: "Pierre-Simon Laplace" },
  "11-16": { q: "Probability is the very guide of life.", who: "Joseph Butler" },
  "11-17": { q: "Facts are stubborn things, but statistics are pliable.", who: "Mark Twain" },
  "11-18": { q: "There are three kinds of lies: lies, damned lies, and statistics.", who: "Mark Twain, attributed to Benjamin Disraeli" },
  "11-19": { q: "A subtle thought that is in error may yet give rise to fruitful inquiry.", who: "Alfred North Whitehead" },
  "11-20": { q: "The purpose of models is not to fit the data but to sharpen the questions.", who: "Samuel Karlin" },
  "11-21": { q: "A theory is something nobody believes, except the person who made it. An experiment is something everybody believes, except the person who made it.", who: "Albert Einstein" },
  "11-22": { q: "The only source of knowledge is experience.", who: "Albert Einstein" },
  "11-23": { q: "Mathematics is well and good but nature keeps dragging us around by the nose.", who: "Albert Einstein" },
  "11-24": { q: "A person who never made a mistake never tried anything new.", who: "Albert Einstein" },
  "11-25": { q: "We cannot solve our problems with the same thinking we used when we created them.", who: "Albert Einstein" },
  "11-26": { q: "Common sense is the collection of prejudices acquired by age eighteen.", who: "Albert Einstein" },
  "11-27": { q: "A problem well stated is a problem half solved.", who: "Charles Kettering" },
  "11-28": { q: "It is the theory which decides what can be observed.", who: "Albert Einstein, to Werner Heisenberg" },
  "11-29": { q: "The formulation of a problem is often more essential than its solution.", who: "Albert Einstein" },
  "11-30": { q: "The important thing is not to stop questioning.", who: "Albert Einstein" },

  /* ---- December ---- */
  "12-01": { q: "Mathematics is the language with which God has written the universe.", who: "Galileo Galilei" },
  "12-02": { q: "Mathematics is a wonderful, mad subject, full of imagination, fantasy and creativity.", who: "Peter Rowlett" },
  "12-03": { q: "Mathematics allows for no hypocrisy and no vagueness.", who: "Stendhal" },
  "12-04": { q: "The mathematician plays a game in which he himself invents the rules.", who: "Ludwig Wittgenstein" },
  "12-05": { q: "A proof is not something that convinces; it is something that compels.", who: "Ludwig Wittgenstein" },
  "12-06": { q: "Whereof one cannot speak, thereof one must be silent.", who: "Ludwig Wittgenstein" },
  "12-07": { q: "The limits of my language mean the limits of my world.", who: "Ludwig Wittgenstein" },
  "12-08": { q: "Everything that can be said can be said clearly.", who: "Ludwig Wittgenstein" },
  "12-09": { q: "Logic is not a body of doctrine, but a mirror-image of the world.", who: "Ludwig Wittgenstein" },
  "12-10": { q: "Mathematics takes us into the region of absolute necessity, to which not only the actual world, but every possible world, must conform.", who: "Bertrand Russell" },
  "12-11": { q: "The point of philosophy is to start with something so simple as not to seem worth stating.", who: "Bertrand Russell" },
  "12-12": { q: "I have always been particularly interested in mathematics because it seemed to me to be the only field in which certainty was attainable.", who: "Bertrand Russell" },
  "12-13": { q: "Pure mathematics consists entirely of assertions to the effect that, if such and such a proposition is true, then such and such another proposition is true.", who: "Bertrand Russell" },
  "12-14": { q: "Ordinary language is totally unsuited for expressing what physics really asserts.", who: "Bertrand Russell" },
  "12-15": { q: "Mathematics, rightly viewed, possesses not only truth, but supreme beauty — a beauty cold and austere, like that of sculpture.", who: "Bertrand Russell" },
  "12-16": { q: "To create a healthy philosophy you should renounce metaphysics but be a good mathematician.", who: "Bertrand Russell" },
  "12-17": { q: "The infinite is nowhere to be found in reality, no matter what experiences and observations are appealed to.", who: "David Hilbert" },
  "12-18": { q: "Six is a perfect number in itself, and not because God created the world in six days; rather the contrary is true.", who: "Saint Augustine" },
  "12-19": { q: "As the sun eclipses the stars by its brilliancy, so the man of knowledge will eclipse the fame of others.", who: "Brahmagupta" },
  "12-20": { q: "A person who can, within a year, solve x squared minus 92 y squared equals 1 is a mathematician.", who: "Brahmagupta" },
  "12-21": { q: "Behold!", who: "Bhāskara II, written under a diagram proving the theorem of Pythagoras" },
  "12-22": { q: "In this quantity, consisting of that which has zero for its divisor, there is no alteration, though many be added or taken away.", who: "Bhāskara II" },
  "12-23": { q: "Whatever is the quotient when the divisor is zero, it is termed an infinite quantity.", who: "Bhāskara II" },
  "12-24": { q: "I am interested in mathematics only as a creative art.", who: "G. H. Hardy" },
  "12-25": { q: "Mathematics is the science which uses easy words for hard ideas.", who: "Edward Kasner" },
  "12-26": { q: "Mathematics is man's own handiwork, subject only to the limitations imposed by the laws of thought.", who: "Edward Kasner" },
  "12-27": { q: "The essence of mathematics is its freedom, and the essence of freedom is choice.", who: "Georg Cantor" },
  "12-28": { q: "An expert problem solver must be endowed with two incompatible qualities: a restless imagination and a patient pertinacity.", who: "Howard W. Eves" },
  "12-29": { q: "What is now proved was once only imagined.", who: "William Blake" },
  "12-30": { q: "The mathematician's pattern, like the painter's or the poet's, must be beautiful; the ideas, like the colours or the words, must fit together in a harmonious way.", who: "G. H. Hardy" },
  "12-31": { q: "I have never done anything useful — judged by that standard, my life has been a complete failure.", who: "G. H. Hardy" }
};
